### ISSUE TITLE
Learn how to operate the data processing pipeline

### ISSUE THREAD

**Issue by kshepard** [PublicMapping/district-builder-2#21]
The Data Analytics ream developed a set of scripts (https://github.com/azavea/districtbuilder-data-pipeline) for pulling in census data and outputting GeoJSON. The task here is to learn how to operate these scripts, and demonstrate that we can use them to output an example GeoJSON file. As a follow-up task, we'd like to make some small modifications to these scripts in order to precisely support our use-case, so gaining familiarity with the inner-workings of the code will be valuable.

Document this process either here or with a README update.

**Comment by maurizi** [comment]
I was able to go follow the README and create new GeoJSON files, both on the current master branch and on the latest refactor (https://github.com/azavea/districtbuilder-data-pipeline/compare/master...lm/docker-reqs-cleanup).

I don't think any additional documentation is necessary right now. I had accumulated a few small fixes when going through the `master` branch that I was going to open a PR for, but those had already been fixed by Luke's changes.
