### ISSUE TITLE
Local Machine setup problem

### ISSUE THREAD

**Issue by g07412** [PublicMapping/district-builder-2#58]
## Detailed Description

I try to setup this code on my local machine and get some error.
1.Unable to download topojson for pa at pa/data/bg-lines.topojson.
2.ENOENT: no such file or directory, stat '/home/node/app/server/dist/server/src/static/index.html'

**Comment by kshepard** [comment]
Thanks for the issue report. Apologies for not being clear, but this repository is in the early stages, and is not yet ready for public use. There are several things that need to be ironed out before it can be used by a wider audience, some of which you've run into here. I'll ping you once it's minimally functional and ready to be worked with. In the meantime, I've updated the README to make a note of this.

**Comment by tgilcrest** [comment]
Hi @g07412 , thanks for reaching out. Like @kshepard said, the app is not ready yet for public use but I would like to hear about your interest in using DistrictBuilder. If you'd like, feel free to reach out to me at tgilcrest@azavea.com and I can give you some more information about the project timeline.

I'm going to close this issue now since we're not yet ready to support setting up the app locally.

**Comment by g07412** [comment]
I am a newbie and trying to learn MERN stack and thought of picking the most difficult one. Let me know if I can at least get a working version where I don't mind if it is an early release.
