### ISSUE TITLE
Write ADR for how district data will be stored

### ISSUE THREAD

**Issue by kshepard** [PublicMapping/district-builder-2#8]
As a continuation of the research task, we should document our findings to demonstrate our chosen approach.

Based on the [research in #7](https://docs.google.com/document/d/1znHcDr1wXQ1vr6cNiI5Y9gl5uwIveVPj659Wpug70Is/edit?usp=sharing) we think TopoJSON is the best approach for merging geometries of the base geo units (blocks, block groups, counties), and the performance is reasonable enough that we think we can store districts as merely a list(s) of IDs of the base geounits, without needing to store the geometries of the districts themselves (we'd calculate them on-the-fly as needed).

Before we settle on this conclusion though, we want to test a more real-world use case that combines geometries of varying levels (e.g. combine Bucks county w/ some block groups & blocks in neighboring counties) and investigate the performance and ease of use of this test case.

**Comment by jfrankl** [comment]
I built a demo that combines geometries of varying levels in a TopoJSON file.

### Process
For TopoJSON to properly understand where larger geounits intersect with smaller, nested geounits, we need the larger geounit features to include all of the vertices found in the smaller geounits. We  can achieve this by using a union function to build the larger geounits from the smaller geounits,  which results in the correct shape but with the additional vertices included. The TopoJSON encoder can now create shared arcs between the larger and smaller geounits.

### Data and Demo
fileshare.internal.azavea.com/users/jfrankl/district-builder/topojson_12_16_19

### Performance
Merge California using only tracts: 125ms
Merge California using only blocks: 2200ms
Merge California using block representation for one tract, and tracts for the rest: 510ms

### Notes
1. I am using tracts instead of blockgroups because it was easier with the data I had available. We should use blockgroups in the final product. Blockgroups and tracts are similar in size.
2. I'm not sure why substituting blocks for one tract results in a 4x slower benchmark. The good news is that for most projects, I users will only use counties, blockgroups, and precincts; being able to combine levels means we'll get major performance benefits over using only blocks.
